spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: QQ29190281951336
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js, *.gif, *.jpg, *.pgn, *.css, *.ico, /druid/*" #不统计这些数据
      stat-view-servlet:
        login-username: druid #访问监控网页的登录用户名
        login-password: druid #访问监控网页的登录密码

  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: localhost:9200

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.jitgur.mall.search: info

logstash:
  host: logstash